### ISSUE TITLE
Github Actions failing

### ISSUE THREAD

**Issue by bayartsogt-ya** [chiehmin/leetcode-ranking-search#13]
Thank you for the great work!
I am wondering if somebody is working on the github action workflow is failing during npm installation

![Screen Shot 2021-12-10 at 5 15 02 PM](https://user-images.githubusercontent.com/43239645/145652821-07f0394a-4dfb-4d09-a140-9eb83f299fab.png)

**Comment by chiehmin** [comment]
I have just fixed the pipeline. Thanks!
