### ISSUE TITLE
rank not matching with leetcode

### ISSUE THREAD

**Issue by dheerajbarnwal** [chiehmin/leetcode-ranking-search#2]
I just checked Weekly contest 194 rank board and its not matching with actual ranking from leetcode.

Can you run your cron one more time in mid of the week.

**Comment by chiehmin** [comment]
@dheeraj92 I just re-run the crawler for contest 194. And I also add more cron jobs to calibrate the contest data (2644a7aa90b6167c6e227766628a5782f28aa696)

Can you check if your ranking for contest 194 is correct now?
