### ISSUE TITLE
Nitpicking: "Retreived" misspelled

### ISSUE THREAD

**Issue by yangjufo** [chiehmin/leetcode-ranking-search#6]
"Retreived" should be "Retrieved", only used the logs though.

For example,
https://github.com/chiehmin/leetcode-ranking-search/blob/master/crawler.py#L21
https://github.com/chiehmin/leetcode-ranking-search/blob/master/crawler.py#L35

**Comment by chiehmin** [comment]
fixed in commit 1d1a850837bca420b1742daa10d15120f08cd51b. thank you
