### ISSUE TITLE
Ranking for BiWeekly Contest 53 not updated

### ISSUE THREAD

**Issue by snehasishroy** [chiehmin/leetcode-ranking-search#8]
Hi,

It seems like the ranking for BiWeekly Contest 53 is not yet updated but the ranking for Weekly Contest 243 is updated. 

Might be due to failed workflow or a bug in the workflow that caused it to not run?

Regards.

**Comment by chiehmin** [comment]
I just manually updated the data of biweekly contest 53. please check it :)

**Comment by snehasishroy** [comment]
Thank you @chiehmin
