### ISSUE TITLE
No Ranking Updates for recent Weekly Contest 248

### ISSUE THREAD

**Issue by cad56** [chiehmin/leetcode-ranking-search#9]
No Ranking Updates for recent Weekly Contest 248, When will they be updated?

**Comment by chiehmin** [comment]
Yes, I am fixing the timeout issue right. Will get the data updated later.

cad56 ***@***.***> 於 2021年7月7日 週三 20:48 寫道：

**Comment by chiehmin** [comment]
Just fixed the issue
